# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: 
  push:
    branches: [ main ]  
    paths:
      - "backend/**"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
    - name: install and test 
      run: |
        npm install    
        npm test        
      working-directory: backend
      
  deploy:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: 159.203.86.45
        USERNAME: root
        PORT: 22
        PASSWORD: IxRg14zeJEJcEpeuxhEL
      with:
        source: "./backend"
        target: "/var/warehouse/makerdao-mips"

    - name: Executing remote  command
      uses: appleboy/ssh-action@master
      with:
        host: 159.203.86.45
        USERNAME: root
        PORT: 22
        PASSWORD: IxRg14zeJEJcEpeuxhEL
        script: | 
          cd /var/warehouse/makerdao-mips/backend
          pm2 stop all
          npm install
          npm run build
          pm2 start all
